/*
 * ArgonOS - rendering the virtual text screen to a VT100 terminal.
 *
 * One of these per console endpoint (UART, USB CDC, each telnet session).
 * Each keeps its own idea of what the far end is currently showing, so a slow
 * or newly attached terminal can repaint at its own pace without holding back
 * the others: a telnet client that connects halfway through simply starts with
 * every row marked dirty.
 *
 * This file is free of kernel and ESP-IDF dependencies so it can be unit
 * tested on a host.
 *
 * Copyright (c) 2026 ArgonOS contributors.  SPDX-License-Identifier: GPL-3.0-or-later
 */
#ifndef ARGON_VTOUT_H
#define ARGON_VTOUT_H

#include <argon/screen.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Receives the generated byte stream; may be called several times per flush. */
typedef void (*ag_vt_sink_fn)(void *ctx, const char *data, size_t len);

typedef struct {
    uint32_t dirty[(AG_SCREEN_MAX_ROWS + 31) / 32];

    /* What we believe the terminal is currently showing. */
    uint16_t last_x;
    uint16_t last_y;
    uint8_t  last_attr;
    bool     cursor_visible;
    bool     synced; /* false until the first full repaint has been sent */

    /*
     * Terminal size, when it is known to differ from the screen (a telnet
     * client reporting 80x24 against an 80x25 screen).  Zero means "same as
     * the screen".
     */
    uint16_t cols;
    uint16_t rows;
} ag_vtout_t;

void ag_vtout_init(ag_vtout_t *o);

/* Requests a full repaint, e.g. when a terminal attaches or resizes. */
void ag_vtout_mark_all(ag_vtout_t *o);

/* Folds the screen's dirty rows into this endpoint's pending set. */
void ag_vtout_take_dirty(ag_vtout_t *o, const ag_screen_t *s);

bool ag_vtout_pending(const ag_vtout_t *o);

/*
 * Emits the smallest sequence that brings the terminal up to date and clears
 * this endpoint's pending set.  Safe to call when nothing is pending: it then
 * only repositions the cursor if it moved.
 */
void ag_vtout_flush(ag_vtout_t *o, const ag_screen_t *s, ag_vt_sink_fn sink,
                    void *ctx);

/* Emits the sequences a terminal needs at attach time (reset, clear, wrap). */
void ag_vtout_hello(ag_vtout_t *o, ag_vt_sink_fn sink, void *ctx);

/* Restores a sane terminal state at detach: default colours, cursor shown. */
void ag_vtout_goodbye(ag_vt_sink_fn sink, void *ctx);

#ifdef __cplusplus
}
#endif

#endif /* ARGON_VTOUT_H */
