#!/usr/bin/env python3
"""Generates the code page tables in components/argon_kernel/src/console/codepage.c.

    python tools/gen-codepage.py

Prints the C block to stdout; paste it in place of the marked section.  The point
of generating it is that nobody types 384 hex values by hand: the mappings come
from Python's own codecs, which come from the Unicode consortium's tables, so a
wrong glyph in the file is a bug in Python rather than a typo here.

Only 0x80..0xff is generated.  Below that all three pages are ASCII, and the
bytes below 0x20 are control characters as far as the screen is concerned - DOS
had graphic shapes there, and reaching them needs a local display with a font of
our own rather than a terminal.
"""

PAGES = [
    ("AG_CP_437", "cp437", "the PC's original: box drawing, no Cyrillic"),
    ("AG_CP_866", "cp866", "MS-DOS Cyrillic, box drawing of 437 kept"),
    ("AG_CP_1251", "cp1251", "Windows Cyrillic: what Russian text files are"),
]


def main():
    print("/* Generated by tools/gen-codepage.py - do not edit by hand. */")
    print("static const uint16_t k_high[AG_CP_COUNT][128] = {")
    for name, codec, note in PAGES:
        print("    /* %s - %s */" % (name, note))
        print("    {")
        for base in range(0x80, 0x100, 8):
            row = []
            for b in range(base, base + 8):
                try:
                    ch = bytes([b]).decode(codec)
                    row.append("0x%04x" % ord(ch))
                except UnicodeDecodeError:
                    # A byte the page does not define at all.  Zero means "no
                    # character", and the renderer shows a space.
                    row.append("0x0000")
            print("        " + ", ".join(row) + ",")
        print("    },")
    print("};")


if __name__ == "__main__":
    main()
