#!/usr/bin/env python3
"""
Recover the 8x8 font the kernel's 8x16 one was built from.

The kernel doubles every scanline of an 8x8 font to fill a 16 pixel cell, so
undoing that is exact: take every other row and nothing is lost.  A panel
driver that has to fit a console onto 240 pixels of height wants the 8 pixel
cell, and it wants these glyphs rather than a smaller set of its own.

What does not work, and was tried first: halving the glyphs horizontally as
well, to get eighty columns onto a 320 pixel panel.  Two source columns OR'd
into one turns every letter with a two pixel stroke and a one pixel gap into a
solid block - 'B' comes out as a filled rectangle.  A console that does not fit
is fixed by making the console forty columns wide, not by making the letters
unreadable.

    python tools/gen_font8x8.py           # writes apps/ili9341/font8x8.h
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "components" / "argon_kernel" / "src" / "dev" / "font8x16.c"
OUT = ROOT / "apps" / "ili9341" / "font8x8.h"

GLYPHS = 256
SRC_ROWS = 16


def load_8x16() -> list[list[int]]:
    text = SRC.read_text(encoding="utf-8")
    rows: list[list[int]] = []
    for m in re.finditer(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){15}0x[0-9A-Fa-f]{2})\s*\}",
                         text):
        vals = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1))]
        if len(vals) == SRC_ROWS:
            rows.append(vals)
    if len(rows) != GLYPHS:
        raise SystemExit(f"expected {GLYPHS} glyphs in {SRC}, found {len(rows)}")
    return rows


def halve_rows(glyph: list[int]) -> list[int]:
    """16 rows -> 8.  OR the pair rather than take the first: that stays
    correct if the 8x16 font ever stops being a doubled 8x8."""
    return [glyph[r] | glyph[r + 1] for r in range(0, SRC_ROWS, 2)]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", default=str(OUT))
    args = ap.parse_args()

    font = [halve_rows(g) for g in load_8x16()]

    lines = [
        "/*",
        " * ArgonOS - 8x8 bitmap font, CP437 cell layout.",
        " *",
        " * Generated by tools/gen_font8x8.py from the kernel's 8x16 font; do",
        " * not edit.  Bit 0 of each row byte is the leftmost pixel.",
        " *",
        " * Copyright (c) 2026 ArgonOS contributors.  SPDX-License-Identifier: GPL-3.0-or-later",
        " */",
        "#ifndef ARGON_FONT8X8_H",
        "#define ARGON_FONT8X8_H",
        "",
        "#include <stdint.h>",
        "",
        "#define AG_FONT8X8_W 8",
        "#define AG_FONT8X8_H 8",
        "",
        "static const uint8_t k_font8x8[256][AG_FONT8X8_H] = {",
    ]
    for i, g in enumerate(font):
        body = ", ".join(f"0x{b:02x}" for b in g)
        lines.append(f"    {{ {body} }}, /* 0x{i:02x} */")
    lines += ["};", "", "#endif /* ARGON_FONT8X8_H */", ""]

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{out}: 256 glyphs, 8x8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
