#!/usr/bin/env python3
"""Generate ArgonOS YM2612 tl/sin/LFO tables (no libm at runtime).

Mirrors init_tables() in apps/md/core/sound/ym2612.c with GW_TARGET=1.
"""
from __future__ import annotations

import math
import pathlib

ENV_BITS = 10
ENV_LEN = 1 << ENV_BITS
ENV_STEP = 128.0 / ENV_LEN
SIN_BITS = 10
SIN_LEN = 1 << SIN_BITS
TL_RES_LEN = 256
TL_TAB_LEN = 13 * 2 * TL_RES_LEN
M_PI = math.pi

# Copied from ym2612.c (lfo_pm_output).
LFO_PM_OUTPUT = [
    # FNUM BIT 4
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1],
    # FNUM BIT 5
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 1, 1, 2, 2, 2, 3],
    # FNUM BIT 6
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 1, 1, 2, 2, 2, 3],
    [0, 0, 2, 3, 4, 4, 5, 6],
    # FNUM BIT 7
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 0, 1, 1, 1, 1, 2],
    [0, 0, 1, 1, 2, 2, 2, 3],
    [0, 0, 2, 3, 4, 4, 5, 6],
    [0, 0, 4, 6, 8, 8, 0xA, 0xC],
    # FNUM BIT 8
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 0, 1, 1, 1, 2, 2],
    [0, 0, 1, 1, 2, 2, 3, 3],
    [0, 0, 1, 2, 2, 2, 3, 4],
    [0, 0, 2, 3, 4, 4, 5, 6],
    [0, 0, 4, 6, 8, 8, 0xA, 0xC],
    [0, 0, 8, 0xC, 0x10, 0x10, 0x14, 0x18],
    # FNUM BIT 9
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 2, 2, 2],
    [0, 0, 0, 2, 2, 2, 4, 4],
    [0, 0, 2, 2, 4, 4, 6, 6],
    [0, 0, 2, 4, 4, 4, 6, 8],
    [0, 0, 4, 6, 8, 8, 0xA, 0xC],
    [0, 0, 8, 0xC, 0x10, 0x10, 0x14, 0x18],
    [0, 0, 0x10, 0x18, 0x20, 0x20, 0x28, 0x30],
    # FNUM BIT 10
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 4, 4, 4, 4],
    [0, 0, 0, 4, 4, 4, 8, 8],
    [0, 0, 4, 4, 8, 8, 0xC, 0xC],
    [0, 0, 4, 8, 8, 8, 0xC, 0x10],
    [0, 0, 8, 0xC, 0x10, 0x10, 0x14, 0x18],
    [0, 0, 0x10, 0x18, 0x20, 0x20, 0x28, 0x30],
    [0, 0, 0x20, 0x30, 0x40, 0x40, 0x50, 0x60],
]


def build_tl() -> list[int]:
    tl = [0] * TL_TAB_LEN
    for x in range(TL_RES_LEN):
        m = (1 << 16) / math.pow(2, (x + 1) * (ENV_STEP / 4.0) / 8.0)
        m = math.floor(m)
        n = int(m)
        n >>= 4
        n = (n >> 1) + 1 if (n & 1) else (n >> 1)
        n <<= 2
        tl[x * 2 + 0] = n
        tl[x * 2 + 1] = -n
        for i in range(1, 13):
            tl[x * 2 + 0 + i * 2 * TL_RES_LEN] = n >> i
            tl[x * 2 + 1 + i * 2 * TL_RES_LEN] = -(n >> i)
    return tl


def build_sin() -> list[int]:
    out = [0] * SIN_LEN
    for i in range(SIN_LEN):
        m = math.sin(((i * 2) + 1) * M_PI / SIN_LEN)
        if m > 0.0:
            o = 8 * math.log(1.0 / m) / math.log(2)
        else:
            o = 8 * math.log(-1.0 / m) / math.log(2)
        o = o / (ENV_STEP / 4)
        n = int(2.0 * o)
        n = (n >> 1) + 1 if (n & 1) else (n >> 1)
        out[i] = n * 2 + (0 if m >= 0.0 else 1)
    return out


def build_lfo_pm() -> list[int]:
    table = [0] * (128 * 8 * 16)
    for i in range(8):
        for fnum in range(128):
            for step in range(8):
                value = 0
                for bit_tmp in range(7):
                    if fnum & (1 << bit_tmp):
                        offset_fnum_bit = bit_tmp * 8
                        value += LFO_PM_OUTPUT[offset_fnum_bit + i][step]
                base = (fnum * 16 * 8) + (i * 16)
                table[base + step + 0] = value
                table[base + (step ^ 7) + 8] = value
    return table


def emit_c_array(name: str, ctype: str, values: list[int], per_line: int = 12) -> str:
    lines = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[i : i + per_line])
        lines.append(f"  {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    root = pathlib.Path(__file__).resolve().parents[1]
    tl = build_tl()
    sin_tab = build_sin()
    lfo = build_lfo_pm()

    ym_out = root / "apps" / "md" / "core" / "sound" / "ym2612_tables_argon.inc"
    ym_text = "\n".join(
        [
            "/* Auto-generated by tools/gen_ym2612_tables.py — do not edit. */",
            emit_c_array("tl_tab", "signed int", tl),
            "",
            emit_c_array("sin_tab", "unsigned int", sin_tab),
            "",
            emit_c_array("lfo_pm_table", "UINT8", lfo, per_line=16),
            "",
        ]
    )
    ym_out.write_text(ym_text, encoding="utf-8", newline="\n")
    print(f"wrote {ym_out} ({ym_out.stat().st_size} bytes)")

    # ag_fm OPN path: sin + tl only (no LFO).
    ag_out = root / "apps" / "common" / "fm" / "ag_fm_ym_tables.inc"
    ag_text = "\n".join(
        [
            "/* Auto-generated by tools/gen_ym2612_tables.py — do not edit. */",
            emit_c_array("ag_fm_tl_tab", "int32_t", tl),
            "",
            emit_c_array("ag_fm_sin_tab", "uint32_t", sin_tab),
            "",
        ]
    )
    ag_out.write_text(ag_text, encoding="utf-8", newline="\n")
    print(f"wrote {ag_out} ({ag_out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
