#!/usr/bin/env python3
"""Generate components/argon_kernel/src/dev/font8x16.c from font8x8_basic.h."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "components" / "argon_kernel" / "src" / "dev" / "font8x16.c"
CACHE = ROOT / "tools" / "_font8x8_basic.h"
URL = "https://raw.githubusercontent.com/dhepper/font8x8/master/font8x8_basic.h"


def load_basic() -> list[list[int]]:
    if not CACHE.exists():
        CACHE.write_bytes(urllib.request.urlopen(URL, timeout=30).read())
    src = CACHE.read_text(encoding="utf-8")
    arrays: list[list[int]] = []
    for m in re.finditer(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,?\s*){8})\}", src):
        vals = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1))]
        if len(vals) == 8:
            arrays.append(vals)
    if len(arrays) < 128:
        raise SystemExit("expected 128 glyphs in font8x8_basic.h, got %d" % len(arrays))
    return arrays[:128]


def build_font(basic: list[list[int]]) -> bytearray:
    font = bytearray(256 * 16)
    for i, g in enumerate(basic):
        for r, b in enumerate(g):
            font[i * 16 + r * 2] = b
            font[i * 16 + r * 2 + 1] = b
    for r in range(16):
        font[0xDB * 16 + r] = 0xFF
        font[0xB0 * 16 + r] = 0x55 if (r % 2) == 0 else 0xAA
        font[0xB1 * 16 + r] = 0xAA if (r % 2) == 0 else 0x55
        font[0xB2 * 16 + r] = 0xFF if (r % 2) == 0 else 0x00
    return font


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", type=pathlib.Path, default=OUT)
    args = ap.parse_args()

    font = build_font(load_basic())
    lines = [
        "/*",
        " * ArgonOS - built-in 8x16 bitmap font (CP437 cell layout).",
        " *",
        " * Glyphs 0..127 derived from font8x8 (Public Domain) by doubling",
        " * each scanline; remaining cells blank except a few block fills.",
        " * Regenerated by tools/gen_font8x16.py.",
        " *",
        " * Copyright (c) 2026 ArgonOS contributors.  SPDX-License-Identifier: Apache-2.0",
        " */",
        '#include "dev/font8x16.h"',
        "",
        "const uint8_t ag_font8x16[256][AG_FONT8X16_H] = {",
    ]
    for i in range(256):
        chunk = font[i * 16 : (i + 1) * 16]
        hexes = ", ".join("0x%02x" % b for b in chunk)
        lines.append("    { %s }, /* %#04x */" % (hexes, i))
    lines.append("};")
    lines.append("")
    args.o.parent.mkdir(parents=True, exist_ok=True)
    args.o.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%u bytes)" % (args.o, args.o.stat().st_size), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
