#!/usr/bin/env python3
"""Generate apps/bigcode/bigcode_body.c with enough .text to force flash XIP."""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "apps" / "bigcode" / "bigcode_body.c"
# ~12 bytes of .text per tiny function on Xtensa after inlining barriers;
# the call table lives in .rodata (data part).  Need >64 KB of .text alone.
N = 7000


def main() -> None:
    lines = [
        "/* Generated by tools/gen_bigcode.py — do not edit. */",
        "#include <stdint.h>",
        "",
    ]
    for i in range(N):
        lines.append(
            "__attribute__((noinline)) static int f%u(int x) { return x + %u; }"
            % (i, i)
        )
    lines.append("")
    lines.append("typedef int (*big_fn)(int);")
    lines.append("static const big_fn k_fns[%u] = {" % N)
    for i in range(N):
        lines.append("    f%u," % i)
    lines.append("};")
    lines.append("")
    lines.append("int bigcode_run(void)")
    lines.append("{")
    lines.append("    int sum = 0;")
    lines.append("    for (unsigned i = 0; i < %uu; i++) {" % N)
    lines.append("        sum += k_fns[i]((int)i);")
    lines.append("    }")
    lines.append("    /* 0+1+...+(N-1) + (0+1+...+(N-1)) = (N-1)*N */")
    lines.append("    const int want = (int)((%uu - 1u) * %uu);" % (N, N))
    lines.append("    return (sum == want) ? 0 : 1;")
    lines.append("}")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%u funcs)" % (OUT, N))


if __name__ == "__main__":
    main()
