#!/usr/bin/env python3
"""Generate components/argon_kernel/src/dev/font8x16.c from font8x8_basic.h.

The source glyphs live in the tree, at third_party/font8x8/font8x8_basic.h,
and that is deliberate: this used to download them on any run without a cache,
which meant a build that reached the internet for the pixels it puts in the
firmware, and it meant the evidence for the public-domain claim in LICENSING.md
lived outside the repository.  Nine kilobytes settles both.

The download is kept only as a way to obtain the file when it is genuinely
absent, and it says out loud when it happens.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "components" / "argon_kernel" / "src" / "dev" / "font8x16.c"
APP_OUT = ROOT / "apps" / "common" / "font8x16.h"
SRC = ROOT / "third_party" / "font8x8" / "font8x8_basic.h"
URL = "https://raw.githubusercontent.com/dhepper/font8x8/master/font8x8_basic.h"


def load_basic() -> list[list[int]]:
    if not SRC.exists():
        print("fetching %s -> %s" % (URL, SRC), file=sys.stderr)
        SRC.parent.mkdir(parents=True, exist_ok=True)
        SRC.write_bytes(urllib.request.urlopen(URL, timeout=30).read())
    src = SRC.read_text(encoding="utf-8")
    arrays: list[list[int]] = []
    for m in re.finditer(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,?\s*){8})\}", src):
        vals = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", m.group(1))]
        if len(vals) == 8:
            arrays.append(vals)
    if len(arrays) < 128:
        raise SystemExit("expected 128 glyphs in font8x8_basic.h, got %d" % len(arrays))
    return arrays[:128]


def build_font(basic: list[list[int]]) -> bytearray:
    font = bytearray(256 * 16)
    for i, g in enumerate(basic):
        for r, b in enumerate(g):
            font[i * 16 + r * 2] = b
            font[i * 16 + r * 2 + 1] = b
    for r in range(16):
        font[0xDB * 16 + r] = 0xFF
        font[0xB0 * 16 + r] = 0x55 if (r % 2) == 0 else 0xAA
        font[0xB1 * 16 + r] = 0xAA if (r % 2) == 0 else 0x55
        font[0xB2 * 16 + r] = 0xFF if (r % 2) == 0 else 0x00
    return font


def app_header(font: bytearray) -> list[str]:
    """The same pixels, as a header an application can include.

    An .AXE cannot link kernel code, so a shell that rasterises its own text -
    the desktop's band backend, which has no surface whose text op it could
    borrow - needs the glyphs in its own image.  Written by this generator
    rather than copied by hand so that there is still one source of truth for
    the pixels; apps/marauder/mrd_font.h predates this and holds its own
    hand-lifted subset.
    """
    lines = [
        "/*",
        " * ArgonOS - 8x16 bitmap font (CP437 cell layout), for applications.",
        " *",
        " * The same table as the kernel's ag_font8x16, in a form an .AXE can",
        " * include: an application cannot link kernel code, and a shell that",
        " * rasterises text itself needs the pixels in its own image.  It rides in",
        " * the image's data part (flash-backed rodata), not the arena.",
        " *",
        " * Glyph data, not code, and nobody's property: font8x8 by Daniel Hepper",
        " * <daniel@hepper.net> (\"License: Public Domain\"), after font8x8.h by",
        " * Marcel Sondaas and International Business Machines.  Scanlines are",
        " * doubled to fill the sixteen-pixel cell, which is mechanical and adds no",
        " * authorship.",
        " *",
        " * Bit 0 (LSB) of each row byte is the leftmost pixel.",
        " * Generated by tools/gen_font8x16.py.  Do not edit.",
        " *",
        " * SPDX-License-Identifier: LicenseRef-PublicDomain",
        " */",
        "#ifndef ARGON_APP_FONT8X16_H",
        "#define ARGON_APP_FONT8X16_H",
        "",
        "#include <stdint.h>",
        "",
        "#define AG_FONT8X16_W 8",
        "#define AG_FONT8X16_H 16",
        "",
        "static const uint8_t k_font8x16[256][AG_FONT8X16_H] = {",
    ]
    for i in range(256):
        chunk = font[i * 16 : (i + 1) * 16]
        hexes = ", ".join("0x%02x" % b for b in chunk)
        lines.append("    { %s }, /* %#04x */" % (hexes, i))
    lines += ["};", "", "#endif /* ARGON_APP_FONT8X16_H */"]
    return lines


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", type=pathlib.Path, default=OUT)
    ap.add_argument(
        "--app-header",
        type=pathlib.Path,
        default=APP_OUT,
        help="also write the app-side header (the same pixels, includable)",
    )
    args = ap.parse_args()

    font = build_font(load_basic())
    lines = [
        "/*",
        " * ArgonOS - built-in 8x16 bitmap font (CP437 cell layout).",
        " *",
        " * Glyph data, not code, and none of it is anybody's property.",
        " *",
        " * Cells 0..127 are font8x8 by Daniel Hepper <daniel@hepper.net>, whose",
        " * own header reads \"License: Public Domain\", itself based on font8x8.h",
        " * by Marcel Sondaas and International Business Machines - the",
        " * public-domain VGA fonts.  Every scanline is doubled here to fill a",
        " * sixteen-pixel cell, which is mechanical and adds no authorship, and so",
        " * is the handful of block cells filled in above 127; those are dedicated",
        " * to the public domain as well, so the whole table is unencumbered.",
        " *",
        " * Said plainly because the alternative was said wrongly for a while: this",
        " * file used to carry GPL-3.0-or-later while its own comment called the",
        " * glyphs public domain, and the generator that writes it said Apache-2.0.",
        " * Three answers for one table of pixels nobody owns.",
        " *",
        " * Bit 0 (LSB) of each row byte is the leftmost pixel (font8x8).",
        " * Regenerated by tools/gen_font8x16.py.  Do not edit.",
        " *",
        " * SPDX-License-Identifier: LicenseRef-PublicDomain",
        " */",
        '#include "dev/font8x16.h"',
        "",
        "const uint8_t ag_font8x16[256][AG_FONT8X16_H] = {",
    ]
    for i in range(256):
        chunk = font[i * 16 : (i + 1) * 16]
        hexes = ", ".join("0x%02x" % b for b in chunk)
        lines.append("    { %s }, /* %#04x */" % (hexes, i))
    lines.append("};")
    lines.append("")
    args.o.parent.mkdir(parents=True, exist_ok=True)
    args.o.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%u bytes)" % (args.o, args.o.stat().st_size), file=sys.stderr)

    if args.app_header is not None:
        args.app_header.parent.mkdir(parents=True, exist_ok=True)
        args.app_header.write_text("\n".join(app_header(font)) + "\n",
                                   encoding="utf-8")
        print("wrote %s (%u bytes)"
              % (args.app_header, args.app_header.stat().st_size),
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
