#!/usr/bin/env python3
"""Build an ArgonOS .AXE application image.

Links the given objects into one contiguous image and writes the .AXE file the
loader expects.  All the awkward work lives here rather than in the kernel: the
device only has to copy the image, add its load bias to a list of 32-bit words,
and jump.

    mkaxe.py --arch xtensa --gcc xtensa-esp32s3-elf-gcc -o HELLO.AXE hello.c

Why only absolute words need fixing: the image is linked as one contiguous
block, so moving it moves every PC-relative instruction together with its
target.  Verified by linking the same object at two bases and diffing - only
the literal-pool words that hold addresses changed.
"""

import argparse
import os
import shutil
import struct
import subprocess
import sys
import tempfile

# Must match sdk/include/argon/axe.h.
MAGIC = b"AXE1"
HEADER_FORMAT = "<4sHHHHI IIII II II II 32s16s32s6I"
ARCHS = {"xtensa": 1, "riscv32": 2}

# Where images are linked.  Any address works; the loader relocates from here.
DEFAULT_LINK_BASE = 0x42000000

# ELF relocation type numbers for a plain absolute 32-bit word.
ABS32_RELOC = {"xtensa": 1, "riscv32": 1}

LINKER_SCRIPT = """\
/* Generated by mkaxe.py - lays the application out as one contiguous image.
 * Literals come first because l32r can only reach backwards. */
ENTRY(ag_main)

SECTIONS
{{
  . = {base:#x};

  .image :
  {{
    *(.literal .literal.*)
    *(.text .text.*)
    *(.rodata .rodata.* .srodata .srodata.*)
    *(.ag_header)
    *(.data .data.* .sdata .sdata.*)
    . = ALIGN(4);
    __ag_bss_start = .;
    *(.bss .bss.* .sbss .sbss.*)
    *(COMMON)
    . = ALIGN(4);
    __ag_bss_end = .;
  }}

  /DISCARD/ :
  {{
    *(.xt.lit) *(.xt.prop) *(.comment) *(.xtensa.info)
    *(.note .note.*) *(.riscv.attributes) *(.eh_frame*)
  }}
}}
"""


def run(cmd, **kwargs):
    """Runs a command, showing it and its output when it fails."""
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        sys.stderr.write("mkaxe: command failed: %s\n" % " ".join(cmd))
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(1)
    return result.stdout


class Elf:
    """Just enough ELF32 to find sections, symbols and relocations."""

    def __init__(self, data):
        self.data = data
        if data[:4] != b"\x7fELF" or data[4] != 1:
            raise SystemExit("mkaxe: not a 32-bit ELF file")
        self.little = data[5] == 1
        e = "<" if self.little else ">"
        # e_shoff, e_flags, e_ehsize, e_phentsize, e_phnum, e_shentsize,
        # e_shnum, e_shstrndx - all of them, because skipping one silently
        # shifts every field after it.
        (self.shoff, _flags, _ehsize, _phentsize, _phnum, self.shentsize,
         self.shnum, self.shstrndx) = struct.unpack_from(e + "IIHHHHHH", data,
                                                        0x20)
        self.endian = e
        self._sections = None

    def sections(self):
        if self._sections is not None:
            return self._sections

        e = self.endian
        raw = []
        for i in range(self.shnum):
            off = self.shoff + i * self.shentsize
            fields = struct.unpack_from(e + "10I", self.data, off)
            raw.append({
                "name_off": fields[0], "type": fields[1], "flags": fields[2],
                "addr": fields[3], "offset": fields[4], "size": fields[5],
                "link": fields[6], "info": fields[7], "align": fields[8],
                "entsize": fields[9],
            })

        strtab = raw[self.shstrndx]
        for s in raw:
            start = strtab["offset"] + s["name_off"]
            end = self.data.index(b"\0", start)
            s["name"] = self.data[start:end].decode("ascii", "replace")

        self._sections = raw
        return raw

    def section(self, name):
        for s in self.sections():
            if s["name"] == name:
                return s
        return None

    def symbols(self):
        """Maps symbol name to value."""
        e = self.endian
        out = {}
        for sec in self.sections():
            if sec["type"] != 2:  # SHT_SYMTAB
                continue
            strtab = self.sections()[sec["link"]]
            count = sec["size"] // 16
            for i in range(count):
                off = sec["offset"] + i * 16
                name_off, value = struct.unpack_from(e + "II", self.data, off)
                if name_off == 0:
                    continue
                start = strtab["offset"] + name_off
                end = self.data.index(b"\0", start)
                out[self.data[start:end].decode("ascii", "replace")] = value
        return out

    def abs32_offsets(self, image_addr, image_size, reloc_type):
        """Image offsets of every absolute 32-bit word the linker resolved.

        These are the only places that depend on where the image ends up.
        """
        e = self.endian
        found = set()
        for sec in self.sections():
            if sec["type"] != 4:  # SHT_RELA
                continue
            target = self.sections()[sec["info"]]
            if target["name"] != ".image":
                continue
            count = sec["size"] // 12
            for i in range(count):
                off = sec["offset"] + i * 12
                r_offset, r_info, _ = struct.unpack_from(e + "IIi", self.data,
                                                         off)
                if (r_info & 0xFF) != reloc_type:
                    continue
                rel = r_offset - image_addr
                if 0 <= rel <= image_size - 4:
                    found.add(rel)
        return sorted(found)


def read_app_header(image, header_addr, image_addr):
    """Pulls the metadata the application declared with AG_APP."""
    if header_addr == 0:
        return {}

    off = header_addr - image_addr
    if off < 0 or off + 0x84 > len(image):
        return {}

    # Must match ag_app_header_t in argon/abi.h.
    (magic, abi_major, abi_minor, flags, stack, heap) = struct.unpack_from(
        "<IHHIII", image, off)
    if magic != struct.unpack("<I", MAGIC)[0]:
        return {}

    def field(at, size):
        raw = image[off + at:off + at + size]
        return raw.split(b"\0")[0].decode("ascii", "replace")

    return {
        "abi_major": abi_major, "abi_minor": abi_minor, "flags": flags,
        "stack_size": stack, "heap_size": heap,
        "name": field(0x14, 32), "version": field(0x34, 16),
        "author": field(0x44, 32),
    }


def main():
    ap = argparse.ArgumentParser(description="Build an ArgonOS .AXE image")
    ap.add_argument("sources", nargs="+", help="C sources or object files")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--arch", choices=sorted(ARCHS), default="xtensa")
    ap.add_argument("--gcc", default="xtensa-esp32s3-elf-gcc")
    ap.add_argument("--include", action="append", default=[],
                    help="added to the include path")
    ap.add_argument("--cflags", default="-Os -ffunction-sections -fdata-sections")
    ap.add_argument("--link-base", type=lambda v: int(v, 0),
                    default=DEFAULT_LINK_BASE)
    ap.add_argument("--keep-elf", help="also write the intermediate ELF here")
    args = ap.parse_args()

    if args.arch == "xtensa":
        # Long calls: the linker cannot shorten a call whose target moves.
        args.cflags += " -mlongcalls"

    workdir = tempfile.mkdtemp(prefix="mkaxe-")
    try:
        objects = []
        for src in args.sources:
            if src.endswith(".o"):
                objects.append(src)
                continue
            obj = os.path.join(workdir, os.path.basename(src) + ".o")
            cmd = [args.gcc, "-c"] + args.cflags.split()
            for inc in args.include:
                cmd += ["-I", inc]
            cmd += [src, "-o", obj]
            run(cmd)
            objects.append(obj)

        script = os.path.join(workdir, "axe.ld")
        with open(script, "w") as f:
            f.write(LINKER_SCRIPT.format(base=args.link_base))

        elf_path = os.path.join(workdir, "image.elf")
        run([args.gcc, "-nostdlib", "-nostartfiles",
             "-Wl,--emit-relocs", "-Wl,-T", script,
             "-Wl,--no-warn-rwx-segments", "-o", elf_path] + objects +
            ["-lgcc"])

        with open(elf_path, "rb") as f:
            elf_data = f.read()
        elf = Elf(elf_data)

        image_sec = elf.section(".image")
        if image_sec is None:
            raise SystemExit("mkaxe: no .image section; check the linker script")

        image_addr = image_sec["addr"]
        image = elf_data[image_sec["offset"]:
                         image_sec["offset"] + image_sec["size"]]

        syms = elf.symbols()
        bss_start = syms.get("__ag_bss_start", image_addr + len(image))
        bss_end = syms.get("__ag_bss_end", bss_start)

        # The file carries everything up to bss; bss is zeroed by the loader.
        file_size = bss_start - image_addr
        image_size = bss_end - image_addr
        if file_size > len(image):
            file_size = len(image)
        stored = image[:file_size]

        entry = syms.get("ag_main")
        if entry is None:
            raise SystemExit("mkaxe: the application defines no ag_main")
        api_slot = syms.get("g_ag_api")
        if api_slot is None:
            raise SystemExit("mkaxe: no g_ag_api; is AG_APP() missing?")

        relocs = elf.abs32_offsets(image_addr, image_size,
                                   ABS32_RELOC[args.arch])
        # A relocation pointing into bss has nothing stored to fix.
        relocs = [r for r in relocs if r + 4 <= file_size]

        meta = read_app_header(image, syms.get("__ag_app_header", 0),
                               image_addr)

        header = struct.pack(
            HEADER_FORMAT, MAGIC,
            meta.get("abi_major", 0), meta.get("abi_minor", 1),
            ARCHS[args.arch], struct.calcsize(HEADER_FORMAT),
            meta.get("flags", 0),
            image_addr, image_size, file_size, struct.calcsize(HEADER_FORMAT),
            entry, api_slot,
            struct.calcsize(HEADER_FORMAT) + file_size, len(relocs),
            meta.get("stack_size", 0), meta.get("heap_size", 0),
            meta.get("name", "").encode()[:31],
            meta.get("version", "").encode()[:15],
            meta.get("author", "").encode()[:31],
            0, 0, 0, 0, 0, 0)

        with open(args.output, "wb") as f:
            f.write(header)
            f.write(stored)
            for r in relocs:
                f.write(struct.pack("<I", r))

        if args.keep_elf:
            shutil.copyfile(elf_path, args.keep_elf)

        print("%s: %s, %u bytes image (%u stored, %u bss), %u relocations" % (
            os.path.basename(args.output), args.arch, image_size, file_size,
            image_size - file_size, len(relocs)))
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    main()
