#!/usr/bin/env python3
"""Build an ArgonOS .AXE application image.

Links the given objects into an image of two parts - code and data - and writes
the .AXE file the loader expects.  All the awkward work lives here rather than in
the kernel: the device only has to copy two blocks, add a bias to a list of
32-bit words, and jump.

    mkaxe.py --arch xtensa --gcc xtensa-esp32s3-elf-gcc -o HELLO.AXE hello.c

Why two parts: code has to live in memory that can be executed, data in memory
that can be written, and on the ESP32 family most memory is one or the other.
Keeping them apart lets the code sit in the small executable arena while the data
lives in PSRAM, megabytes of it.

Constants go with the data, not with the code: a font or a bitmap is read, never
executed, and there is no reason for it to take up the arena.  --rodata code
puts them back, and AG_HOT_RODATA keeps one object in the code part - which is
internal SRAM - when its latency matters more than the space it costs.

Why only absolute words need fixing: each part is linked as one contiguous
block, so moving it moves every PC-relative instruction together with its target.
Verified by linking the same source at two pairs of bases and diffing - only the
words that hold addresses changed.

The two parts move independently, so every relocation says which part its word
lives in and which part the address in that word points into.  Both fit in the
low two bits of the offset, which are free because the offsets are word aligned.

RISC-V is built contiguous instead: with the medany code model its code reaches
its data PC-relatively, so the distance between the parts is part of the
contract and the loader is told to keep them adjacent.
"""

import argparse
import os
import shutil
import struct
import subprocess
import sys
import tempfile

# Must match sdk/include/argon/axe.h.
MAGIC = b"AXE1"
HEADER_FORMAT = "<4sHHHHI IIII IIII II II II 32s16s32s6I"
ARCHS = {"xtensa": 1, "riscv32": 2}

# Must match enum ag_axe_flags in sdk/include/argon/abi.h.
AG_AXE_DRIVER = 1 << 3
AG_AXE_CONTIGUOUS = 1 << 5

# Relocation entry bits, must match AG_AXE_R_* in axe.h.
R_IN_DATA = 0x1
R_TO_DATA = 0x2

# Where parts are linked by default: the windows they are meant to end up in,
# far enough apart that no address is ambiguous.  Any addresses work; the loader
# relocates from these.
DEFAULT_CODE_BASE = 0x42000000
DEFAULT_DATA_BASE = 0x3C000000

# ELF relocation type numbers for a plain absolute 32-bit word.
ABS32_RELOC = {"xtensa": 1, "riscv32": 1}

SHT_SYMTAB = 2
SHT_RELA = 4
SHT_NOBITS = 8

CODE_SECTION = ".image"
DATA_SECTION = ".dimage"

# Where the constants go needs nothing from the kernel: code reaches one through a
# literal holding its absolute address, and that literal is relocated by the data
# bias like any other word pointing into the data part.  The price of the default
# is a read from PSRAM (cached) instead of SRAM, and the loss of read-only, which
# without an MPU was never enforced anyway.
RODATA_INPUT = "*(.rodata .rodata.* .srodata .srodata.*)"
HOT_RODATA_INPUT = "*(.hot_rodata .hot_rodata.*)"

LINKER_SCRIPT = """\
/* Generated by mkaxe.py - lays the application out as two contiguous parts. */
ENTRY(__ag_app_header)

SECTIONS
{{
{body}
  /DISCARD/ :
  {{
    *(.xt.lit) *(.xt.prop) *(.comment) *(.xtensa.info)
    *(.note .note.*) *(.riscv.attributes) *(.eh_frame*)
  }}
}}
"""


def rodata_lines():
    """The constants, bracketed by symbols so their size can be reported.

    The trailing ALIGN keeps whatever follows word aligned, and puts the padding
    inside the reported size rather than leaving it unaccounted for.
    """
    return ["    __ag_rodata_start = .;",
            "    " + RODATA_INPUT,
            "    . = ALIGN(4);",
            "    __ag_rodata_end = .;"]


def code_block(rodata_in_code):
    """The part that gets executed.  Literals first: l32r only reaches back."""
    lines = ["  .image :", "  {",
             "    *(.literal .literal.*)",
             "    *(.text .text.*)",
             "    " + HOT_RODATA_INPUT]
    if rodata_in_code:
        lines += rodata_lines()
    lines += ["    *(.ag_header)",
              "    . = ALIGN(4);",
              "  }"]
    return "\n".join(lines) + "\n"


def data_block(rodata_in_code):
    """The part that gets written - and read, which is why constants fit here."""
    lines = ["  .dimage :", "  {"]
    if not rodata_in_code:
        lines += rodata_lines()
    lines += ["    *(.data .data.* .sdata .sdata.*)",
              "    . = ALIGN(4);",
              "    __ag_bss_start = .;",
              "    *(.bss .bss.* .sbss .sbss.*)",
              "    *(COMMON)",
              "    . = ALIGN(4);",
              "    __ag_bss_end = .;",
              "  }"]
    return "\n".join(lines) + "\n"


def linker_script(code_base, data_base, contiguous, rodata_in_code):
    """The script for one layout.

    Sections are emitted in address order, so that the ELF's own segments come
    out monotonic and readable in a dump.  The parts are found by name rather
    than by position, so the ordering costs nothing; ld links them either way,
    which was checked rather than assumed.
    """
    code = code_block(rodata_in_code)
    data = data_block(rodata_in_code)

    if contiguous:
        # The data follows the code.  ALIGN covers whatever alignment the data
        # itself asks for, so the gap the linker inserts is bounded and known;
        # it is then folded into the code part, because the loader is promised
        # that the data starts exactly where the code ends.
        blocks = ["  . = %#x;\n" % code_base, code,
                  "  . = ALIGN(16);\n", data]
    else:
        parts = [(code_base, code), (data_base, data)]
        parts.sort(key=lambda p: p[0])
        blocks = []
        for base, block in parts:
            blocks.append("  . = %#x;\n" % base)
            blocks.append(block)

    return LINKER_SCRIPT.format(body="\n".join(blocks))


def run(cmd, **kwargs):
    """Runs a command, showing it and its output when it fails."""
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        sys.stderr.write("mkaxe: command failed: %s\n" % " ".join(cmd))
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(1)
    return result.stdout


class Elf:
    """Just enough ELF32 to find sections, symbols and relocations."""

    def __init__(self, data):
        self.data = data
        if data[:4] != b"\x7fELF" or data[4] != 1:
            raise SystemExit("mkaxe: not a 32-bit ELF file")
        self.little = data[5] == 1
        e = "<" if self.little else ">"
        # e_shoff, e_flags, e_ehsize, e_phentsize, e_phnum, e_shentsize,
        # e_shnum, e_shstrndx - all of them, because skipping one silently
        # shifts every field after it.
        (self.shoff, _flags, _ehsize, _phentsize, _phnum, self.shentsize,
         self.shnum, self.shstrndx) = struct.unpack_from(e + "IIHHHHHH", data,
                                                        0x20)
        self.endian = e
        self._sections = None
        self._symtabs = {}

    def sections(self):
        if self._sections is not None:
            return self._sections

        e = self.endian
        raw = []
        for i in range(self.shnum):
            off = self.shoff + i * self.shentsize
            fields = struct.unpack_from(e + "10I", self.data, off)
            raw.append({
                "index": i,
                "name_off": fields[0], "type": fields[1], "flags": fields[2],
                "addr": fields[3], "offset": fields[4], "size": fields[5],
                "link": fields[6], "info": fields[7], "align": fields[8],
                "entsize": fields[9],
            })

        strtab = raw[self.shstrndx]
        for s in raw:
            start = strtab["offset"] + s["name_off"]
            end = self.data.index(b"\0", start)
            s["name"] = self.data[start:end].decode("ascii", "replace")

        self._sections = raw
        return raw

    def section(self, name):
        for s in self.sections():
            if s["name"] == name:
                return s
        return None

    def symbol_table(self, sec_index):
        """Symbols of one symtab, by index: name, value and defining section."""
        if sec_index in self._symtabs:
            return self._symtabs[sec_index]

        e = self.endian
        sec = self.sections()[sec_index]
        strtab = self.sections()[sec["link"]]
        out = []
        for i in range(sec["size"] // 16):
            off = sec["offset"] + i * 16
            name_off, value, _size, _info, _other, shndx = struct.unpack_from(
                e + "IIIBBH", self.data, off)
            name = ""
            if name_off != 0:
                start = strtab["offset"] + name_off
                end = self.data.index(b"\0", start)
                name = self.data[start:end].decode("ascii", "replace")
            out.append({"name": name, "value": value, "shndx": shndx})

        self._symtabs[sec_index] = out
        return out

    def symbols(self):
        """Maps symbol name to value, across every symbol table."""
        out = {}
        for sec in self.sections():
            if sec["type"] != SHT_SYMTAB:
                continue
            for sym in self.symbol_table(sec["index"]):
                if sym["name"]:
                    out[sym["name"]] = sym["value"]
        return out

    def abs32_relocs(self, reloc_type, targets):
        """Every absolute 32-bit word the linker resolved, classified.

        `targets` maps a section index to a part description.  Yields
        (location part, offset in it, target part) for each word that depends on
        where the parts end up - the only places the loader has to touch.
        """
        e = self.endian
        for sec in self.sections():
            if sec["type"] != SHT_RELA or sec["info"] not in targets:
                continue

            where = targets[sec["info"]]
            syms = self.symbol_table(sec["link"])

            for i in range(sec["size"] // 12):
                off = sec["offset"] + i * 12
                r_offset, r_info, _addend = struct.unpack_from(e + "IIi",
                                                               self.data, off)
                if (r_info & 0xFF) != reloc_type:
                    continue

                sym_index = r_info >> 8
                if sym_index >= len(syms):
                    raise SystemExit("mkaxe: relocation names symbol %u, which "
                                     "the symbol table does not have" % sym_index)
                shndx = syms[sym_index]["shndx"]
                if shndx not in targets:
                    raise SystemExit(
                        "mkaxe: %s refers to symbol '%s', which is not in the "
                        "image; an application may only reference itself and "
                        "the API table" % (where["name"],
                                           syms[sym_index]["name"] or "?"))

                yield (where, r_offset - where["addr"], targets[shndx])


def read_app_header(image, header_addr, image_addr):
    """Pulls the metadata the application declared with AG_APP."""
    if header_addr == 0:
        return {}

    off = header_addr - image_addr
    if off < 0 or off + 0x84 > len(image):
        return {}

    # Must match ag_app_header_t in argon/abi.h.
    (magic, abi_major, abi_minor, flags, stack, heap) = struct.unpack_from(
        "<IHHIII", image, off)
    if magic != struct.unpack("<I", MAGIC)[0]:
        return {}

    def field(at, size):
        raw = image[off + at:off + at + size]
        return raw.split(b"\0")[0].decode("ascii", "replace")

    return {
        "abi_major": abi_major, "abi_minor": abi_minor, "flags": flags,
        "stack_size": stack, "heap_size": heap,
        "name": field(0x14, 32), "version": field(0x34, 16),
        "author": field(0x44, 32),
    }


def part_of(elf, name, is_data):
    """Describes one output section as a part of the image.

    Absent sections are still described, as an empty part: an application with
    no writable statics at all is a legitimate application.
    """
    sec = elf.section(name)
    if sec is None:
        return {"name": name, "index": -1, "addr": 0, "size": 0, "stored": b"",
                "is_data": is_data}

    # A section that is all bss carries nothing in the file, and its file offset
    # points at whatever happens to follow.  Reading it would be reading noise.
    stored = b""
    if sec["type"] != SHT_NOBITS:
        stored = elf.data[sec["offset"]:sec["offset"] + sec["size"]]

    return {"name": name, "index": sec["index"], "addr": sec["addr"],
            "size": sec["size"], "stored": stored, "is_data": is_data}


def main():
    ap = argparse.ArgumentParser(description="Build an ArgonOS .AXE image")
    ap.add_argument("sources", nargs="+", help="C sources or object files")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--arch", choices=sorted(ARCHS), default="xtensa")
    ap.add_argument("--gcc", default="xtensa-esp32s3-elf-gcc")
    ap.add_argument("--include", action="append", default=[],
                    help="added to the include path")
    ap.add_argument("--cflags", default="-Os -ffunction-sections -fdata-sections")
    ap.add_argument("--code-base", type=lambda v: int(v, 0),
                    default=DEFAULT_CODE_BASE)
    ap.add_argument("--data-base", type=lambda v: int(v, 0),
                    default=DEFAULT_DATA_BASE)
    ap.add_argument("--contiguous", action="store_true",
                    help="one block, data straight after code (implied on "
                         "riscv32, whose code reaches data PC-relatively)")
    ap.add_argument("--rodata", choices=("data", "code"), default="data",
                    help="which part read-only constants go in; data (the "
                         "default) keeps fonts, images and tables out of the "
                         "code arena, code puts them back in SRAM for latency. "
                         "AG_HOT_RODATA does the same for one object")
    ap.add_argument("--libs", action="append", default=[],
                    help="extra archives to link against, by name and without "
                         "the -l (libgcc is always linked). Only members that "
                         "resolve a still-undefined symbol are pulled in, so "
                         "asking for c to get setjmp does not drag newlib's "
                         "malloc past the app's own")
    ap.add_argument("--keep-elf", help="also write the intermediate ELF here")
    ap.add_argument(
        "--no-stage",
        action="store_true",
        help="do not also copy the image into build/apps and build/sd_card",
    )
    args = ap.parse_args()

    if args.arch == "xtensa":
        # Long calls: the linker cannot shorten a call whose target moves.
        args.cflags += " -mlongcalls"
    else:
        # PC-relative addressing throughout, which is why this arch is built as
        # one block: the distance between code and data must not change.
        args.cflags += " -mcmodel=medany"
        args.contiguous = True

    workdir = tempfile.mkdtemp(prefix="mkaxe-")
    try:
        objects = []
        for src in args.sources:
            if src.endswith(".o"):
                objects.append(src)
                continue
            obj = os.path.join(workdir, os.path.basename(src) + ".o")
            cmd = [args.gcc, "-c"] + args.cflags.split()
            for inc in args.include:
                cmd += ["-I", inc]
            cmd += [src, "-o", obj]
            run(cmd)
            objects.append(obj)

        rodata_in_code = args.rodata == "code"

        script = os.path.join(workdir, "axe.ld")
        with open(script, "w") as f:
            f.write(linker_script(args.code_base, args.data_base,
                                  args.contiguous, rodata_in_code))

        elf_path = os.path.join(workdir, "image.elf")
        run([args.gcc, "-nostdlib", "-nostartfiles",
             "-Wl,--emit-relocs", "-Wl,-T", script,
             "-Wl,--no-warn-rwx-segments", "-o", elf_path] + objects +
            ["-l" + lib for lib in args.libs] + ["-lgcc"])

        with open(elf_path, "rb") as f:
            elf_data = f.read()
        elf = Elf(elf_data)

        code = part_of(elf, CODE_SECTION, is_data=False)
        if code["size"] == 0:
            raise SystemExit("mkaxe: no code in the image; check the linker "
                             "script")
        data = part_of(elf, DATA_SECTION, is_data=True)

        syms = elf.symbols()

        # The data part carries everything up to bss; bss is zeroed by the
        # loader, so it is sized but not stored.
        if data["size"] > 0:
            bss_start = syms.get("__ag_bss_start", data["addr"] + data["size"])
            bss_end = syms.get("__ag_bss_end", bss_start)
            data_stored = min(bss_start - data["addr"], len(data["stored"]))
            data["size"] = max(bss_end - data["addr"], data_stored)
            data["stored"] = data["stored"][:data_stored]

        if args.contiguous and data["size"] > 0:
            # The loader places the data immediately after the code, so any
            # alignment padding the linker left between them belongs to the code
            # part.  Otherwise the two disagree about where the data begins.
            gap = data["addr"] - (code["addr"] + code["size"])
            if gap < 0:
                raise SystemExit("mkaxe: the parts overlap; check the linker "
                                 "script")
            code["size"] += gap
            code["stored"] += b"\0" * gap

        api_slot = syms.get("g_ag_api")
        if api_slot is None:
            raise SystemExit("mkaxe: no g_ag_api; is AG_APP() / AG_DRV() missing?")

        targets = {p["index"]: p for p in (code, data) if p["index"] >= 0}
        relocs = set()
        for where, offset, points_to in elf.abs32_relocs(
                ABS32_RELOC[args.arch], targets):
            if offset < 0 or offset + 4 > len(where["stored"]):
                # Either outside the part, or in its bss - where there is
                # nothing stored to fix, and zero is already the right value.
                continue
            if offset % 4 != 0:
                raise SystemExit("mkaxe: unaligned absolute word at %s+%#x" % (
                    where["name"], offset))

            # Cross-check the tool against itself: the word the linker stored
            # must already point into the part the symbol says it does.
            value = struct.unpack_from("<I", where["stored"], offset)[0]
            low = points_to["addr"]
            high = low + points_to["size"]
            if not low <= value <= high:
                raise SystemExit(
                    "mkaxe: %s+%#x holds %#x, which is outside %s (%#x..%#x)"
                    % (where["name"], offset, value, points_to["name"], low,
                       high))

            entry_word = offset
            if where["is_data"]:
                entry_word |= R_IN_DATA
            if points_to["is_data"]:
                entry_word |= R_TO_DATA
            relocs.add(entry_word)

        relocs = sorted(relocs)

        meta = read_app_header(code["stored"], syms.get("__ag_app_header", 0),
                               code["addr"])

        flags = meta.get("flags", 0)
        if args.contiguous and data["size"] > 0:
            # With no data part there is nothing to keep adjacent, and the flag
            # would only describe a promise about a part that does not exist.
            flags |= AG_AXE_CONTIGUOUS

        # A .SYS provides ag_driver_init; an application provides ag_main.  The
        # flag in the header decides when both exist; when only the driver entry
        # is present the flag is implied so a forgotten AG_AXE_DRIVER still
        # loads as a module rather than as a broken application.
        if flags & AG_AXE_DRIVER:
            entry = syms.get("ag_driver_init")
            if entry is None:
                raise SystemExit(
                    "mkaxe: AG_AXE_DRIVER is set but there is no ag_driver_init")
        elif "ag_driver_init" in syms and "ag_main" not in syms:
            entry = syms["ag_driver_init"]
            flags |= AG_AXE_DRIVER
        else:
            entry = syms.get("ag_main")
            if entry is None:
                raise SystemExit(
                    "mkaxe: the image defines neither ag_main nor "
                    "ag_driver_init")

        header_size = struct.calcsize(HEADER_FORMAT)
        code_offset = header_size
        data_offset = code_offset + len(code["stored"])
        reloc_offset = data_offset + len(data["stored"])

        header = struct.pack(
            HEADER_FORMAT, MAGIC,
            meta.get("abi_major", 0), meta.get("abi_minor", 1),
            ARCHS[args.arch], header_size, flags,
            code["addr"], code["size"], len(code["stored"]), code_offset,
            data["addr"], data["size"], len(data["stored"]), data_offset,
            entry, api_slot,
            reloc_offset, len(relocs),
            meta.get("stack_size", 0), meta.get("heap_size", 0),
            meta.get("name", "").encode()[:31],
            meta.get("version", "").encode()[:15],
            meta.get("author", "").encode()[:31],
            0, 0, 0, 0, 0, 0)

        with open(args.output, "wb") as f:
            f.write(header)
            f.write(code["stored"])
            f.write(data["stored"])
            for r in relocs:
                f.write(struct.pack("<I", r))

        if args.keep_elf:
            shutil.copyfile(elf_path, args.keep_elf)

        # Constants are worth their own number: they are the part of an image
        # that grows without bound, and where they went decides whether that
        # growth costs arena or PSRAM.
        rodata_bytes = (syms.get("__ag_rodata_end", 0) -
                        syms.get("__ag_rodata_start", 0))

        print("%s: %s%s, code %u bytes, data %u bytes (%u stored, %u bss), "
              "%u bytes of constants in the %s part, %u relocations" % (
                  os.path.basename(args.output), args.arch,
                  " contiguous" if args.contiguous else "",
                  code["size"], data["size"], len(data["stored"]),
                  data["size"] - len(data["stored"]), rodata_bytes,
                  args.rodata, len(relocs)))

        if not args.no_stage:
            stage_image(args.output)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def repo_root():
    """Directory that contains tools/mkaxe.py (repo root)."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def stage_image(path):
    """
    Canonical layout: every .AXE / .SYS also lands in build/apps (archive) and
    build/sd_card (HostFS / sync share). Prefer -o build/apps/NAME.AXE; staging
    still runs so rebuilds always refresh the share.
    """
    src = os.path.abspath(path)
    if not os.path.isfile(src):
        return
    name = os.path.basename(src)
    root = repo_root()
    apps = os.path.join(root, "build", "apps")
    share = os.path.join(root, "build", "sd_card")
    os.makedirs(apps, exist_ok=True)
    os.makedirs(share, exist_ok=True)
    for dest_dir in (apps, share):
        dest = os.path.join(dest_dir, name)
        if os.path.abspath(dest) == src:
            continue
        shutil.copy2(src, dest)
    print("staged -> build/apps/%s, build/sd_card/%s" % (name, name))


if __name__ == "__main__":
    main()
