#!/usr/bin/env python3
"""Turn apps/phone/web/index.html into the C array PHONE.SYS serves.

The board serves its own client, so the page has to be in the image.  It is
kept as a real .html file - editable, openable in a browser against a board
that is already running, and reviewable as HTML rather than as a wall of hex -
and this turns it into apps/phone/page.h.

Run by `argon apps` before PHONE.SYS is compiled (the "generate" key in
tools/apps.json), so a page edited and not regenerated cannot ship.  Also fine
to run by hand:

    python tools/mkpage.py

The page is emitted verbatim and then gzipped, which is not the same as
minified and is the reason it need not be.  A minifier that gets JavaScript
subtly wrong produces a page that fails in a browser nobody here has; gzip
cannot change a byte of it.  The browser decompresses, so the board spends
nothing - it serves the stored bytes with Content-Encoding: gzip and never sees
the original.  "View source" on the phone still shows the real page, comments
and all, because that is what arrives.

And it is not a nicety.  A .SYS keeps its data in RAM, so forty kilobytes of
page is forty kilobytes of a board that may only have a hundred and ten free -
on the CYD that is the difference between the desktop starting and not, since
DESKTOP.AXE wants seventy-one of them in one piece.  Gzip takes the page to
about a quarter of that.
"""
import gzip
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "apps", "phone", "web", "index.html")
DST = os.path.join(ROOT, "apps", "phone", "page.h")

HEAD = """/*
 * ArgonOS - the page PHONE.SYS serves, as bytes.
 *
 * GENERATED by tools/mkpage.py from apps/phone/web/index.html.  Do not edit:
 * edit the HTML and run `argon apps --only PHONE.SYS`, which regenerates this
 * on the way past.
 *
 * These are the GZIPPED bytes, served with Content-Encoding: gzip.  The board
 * never decompresses them - the browser does - so this costs the board nothing
 * but stores a quarter of what the page weighs, and a .SYS keeps its data in
 * RAM.  On a board with a hundred and ten kilobytes free that is the whole
 * difference between an application starting and not.
 *
 * Copyright (c) 2026 ArgonOS contributors.  SPDX-License-Identifier: Apache-2.0
 */
#ifndef AG_PHONE_PAGE_H
#define AG_PHONE_PAGE_H

#include <stdint.h>

/* %u bytes of HTML, gzipped to this. */
#define AG_PHONE_PAGE_LEN %uu
#define AG_PHONE_PAGE_GZIP 1

static const char ag_phone_page[AG_PHONE_PAGE_LEN + 1u] =
"""

TAIL = """;

#endif /* AG_PHONE_PAGE_H */
"""


def c_escape(chunk):
    out = []
    for b in chunk:
        c = chr(b)
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif b == 0x09:
            out.append("\\t")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            # Octal, not hex: "\xNN" swallows the next character when it happens
            # to be a hex digit, which in a page full of colours it often is.
            out.append("\\%03o" % b)
    return "".join(out)


def main():
    with open(SRC, "rb") as f:
        page = f.read()

    # CRLF would be served as-is and is harmless in HTML, but it makes the byte
    # count depend on how git checked the file out - and the Content-Length has
    # to be right or the browser waits for bytes that never come.
    page = page.replace(b"\r\n", b"\n")
    raw_len = len(page)

    # mtime=0 so that the same page produces the same bytes: a generated file
    # that changes on every run is one that shows up in every diff and rebuilds
    # the image for nothing.
    page = gzip.compress(page, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(page), 40):
        lines.append('    "%s"' % c_escape(page[i:i + 40]))

    text = (HEAD % (raw_len, len(page))) + "\n".join(lines) + TAIL

    old = None
    if os.path.exists(DST):
        with open(DST, "r", encoding="utf-8", newline="") as f:
            old = f.read()
    if old == text:
        return 0

    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("mkpage: %s -> %s (%u bytes of HTML, %u gzipped)" %
          (os.path.relpath(SRC, ROOT), os.path.relpath(DST, ROOT), raw_len,
           len(page)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
