#!/usr/bin/env python3
"""Turn apps/phone/web/index.html into the C array PHONE.SYS serves.

The board serves its own client, so the page has to be in the image.  It is
kept as a real .html file - editable, openable in a browser against a board
that is already running, and reviewable as HTML rather than as a wall of hex -
and this turns it into apps/phone/page.h.

Run by `argon apps` before PHONE.SYS is compiled (the "generate" key in
tools/apps.json), so a page edited and not regenerated cannot ship.  Also fine
to run by hand:

    python tools/mkpage.py

The page is emitted verbatim: not minified, comments and all.  Two reasons, and
neither is laziness.  A minifier that gets JavaScript subtly wrong produces a
page that fails in a browser nobody has here, and the saving is a few kilobytes
of the one resource this system has plenty of - flash is four megabytes against
three hundred and twenty kilobytes of RAM.  And "view source" on the phone then
shows the page that is actually running, which is the only debugger available
on the far side of this link.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "apps", "phone", "web", "index.html")
DST = os.path.join(ROOT, "apps", "phone", "page.h")

HEAD = """/*
 * ArgonOS - the page PHONE.SYS serves, as bytes.
 *
 * GENERATED by tools/mkpage.py from apps/phone/web/index.html.  Do not edit:
 * edit the HTML and run `argon apps --only PHONE.SYS`, which regenerates this
 * on the way past.
 *
 * Copyright (c) 2026 ArgonOS contributors.  SPDX-License-Identifier: Apache-2.0
 */
#ifndef AG_PHONE_PAGE_H
#define AG_PHONE_PAGE_H

#include <stdint.h>

#define AG_PHONE_PAGE_LEN %uu

static const char ag_phone_page[AG_PHONE_PAGE_LEN + 1u] =
"""

TAIL = """;

#endif /* AG_PHONE_PAGE_H */
"""


def c_escape(chunk):
    out = []
    for b in chunk:
        c = chr(b)
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif b == 0x09:
            out.append("\\t")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            # Octal, not hex: "\xNN" swallows the next character when it happens
            # to be a hex digit, which in a page full of colours it often is.
            out.append("\\%03o" % b)
    return "".join(out)


def main():
    with open(SRC, "rb") as f:
        page = f.read()

    # CRLF would be served as-is and is harmless in HTML, but it makes the byte
    # count depend on how git checked the file out - and the Content-Length has
    # to be right or the browser waits for bytes that never come.
    page = page.replace(b"\r\n", b"\n")

    lines = []
    for i in range(0, len(page), 40):
        lines.append('    "%s"' % c_escape(page[i:i + 40]))

    text = (HEAD % len(page)) + "\n".join(lines) + TAIL

    old = None
    if os.path.exists(DST):
        with open(DST, "r", encoding="utf-8", newline="") as f:
            old = f.read()
    if old == text:
        return 0

    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("mkpage: %s -> %s (%u bytes)" %
          (os.path.relpath(SRC, ROOT), os.path.relpath(DST, ROOT), len(page)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
